import os
import arcpy

# GET REPORT FROM ACCELA WITH THESE FIELDS:  PARCEL NUMBER, SURVEY ID, SUMMARY, DESCRIPTION, SURVEY YEAR





# CODE FROM MODELBUILDER:  SELECT PARCELS BY PARCEL NUMBER.  SELECT, COPY, PASTE TO SURVEY PLAT LAYER.  ENTER ATTRIBUTES FROM ACCELA TABLE.  SAVE EDITS.





# LOOP THROUGH ALL, PASS SURVEYS WITH NO PARCEL ID





# COPY PDF FROM PLANSCAN FODLER TO SURVEYS FOLDER.  RENAME.





# MARK MAPPED IN ACCELA




# EMAIL REPORT OF WHAT WAS PROCESSED AND WHAT WAS NOT (AND NEEDS DONE MANUALLY)
